In [4]:
import pandas as pd
import numpy as np
import math

In [13]:
df = pd.read_csv('Book1.csv')
df

                 Patient                Product
0                      S  UNIENZYME TAB
1                      S  VELOZ D CAP
2     SAINATH SHIVAJI M   INJ OROFER S 100
3     JAGATAP BHIKAJI N   INJ ALKEMCORT-H
4     JAGATAP BHIKAJI N   BLOOD SET
...                  ...                    ...
9746  WANI POPAT          C FURO CV 625 TAB
9747  WANI POPAT          ETOZOX 90 TAB
9748  WANI POPAT          REBORUL 20 TAB
9749  WANI POPAT          LYCOCHEER FORTE TAB
9750  patil               CLAVAM 625

[9751 rows x 2 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9751 entries, 0 to 9750
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Patient  9751 non-null   object
 1   Product  9751 non-null   object
dtypes: object(2)
memory usage: 152.5+ KB

In [15]:
df.columns

Index(['Patient', 'Product'], dtype='object')

In [16]:
from mlxtend.frequent_patterns import association_rules, apriori

In [17]:
transactions_str = df.groupby(['Patient', 'Product'])['Product'].count().reset_index(name ='Count')
transactions_str

                 Patient                Product  Count
0                         B PROTIN (CHOC)            1
1                         BEVON SUSPENSION           1
2                         CEFIX 200 DT               1
3                         DOLONEX   20MG  DT         1
4                         HCQS 200 TAB               1
...                  ...                    ...    ...
8404  yadhav              INJ MCOB PLUS              2
8405  yadhav              INJ ROZID 1GM              2
8406  yadhav              LIV 52 TAB                 1
8407  zhorale baby r      ETHILON 1 NW3348           1
8408  zhorale baby r      PROLINE MESH 15*15         1

[8409 rows x 3 columns]

In [18]:
# making a mxn matrice where m=transaction and n=items and each row represents whether the item was in the transaction or not
my_basket = transactions_str.pivot_table(index='Patient', columns='Product', values='Count', aggfunc='sum').fillna(0)


my_basket.head()

Product,10,10ML SYRING,20ML SYRINGE,2ML SYRINGE,3 WAY POLYMED,3WAY STOPCOCK,4 QUIN PFS 0.5,4QUIN D EYE DROP,5 ML SYRING,A TO Z NS SYRUP(B),...,ZINCOVIT TAB,ZOCLAR 250 TAB,ZOFIX CV 200 TAB,ZORYL M 1,ZOSTER 400TAB,ZOSTER 800 TAB,ZURACEF 200 TAB,ZYLORIC 100 TAB,ZYLORIC 300,ZYTEE GEL 10 GM
Patient,,,,,,,,,,,,,,,,,,,,,
,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
SHANKAR SHINDE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
VISHA KUNAL INGA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
# making a function which returns 0 or 1
# 0 means item was not in that transaction, 1 means item present in that transaction

def encode(x):
    if x<=0:
        return 0
    if x>=1:
        return 1

# applying the function to the dataset

my_basket_sets = my_basket.applymap(encode)
my_basket_sets.head()

Product,10,10ML SYRING,20ML SYRINGE,2ML SYRINGE,3 WAY POLYMED,3WAY STOPCOCK,4 QUIN PFS 0.5,4QUIN D EYE DROP,5 ML SYRING,A TO Z NS SYRUP(B),...,ZINCOVIT TAB,ZOCLAR 250 TAB,ZOFIX CV 200 TAB,ZORYL M 1,ZOSTER 400TAB,ZOSTER 800 TAB,ZURACEF 200 TAB,ZYLORIC 100 TAB,ZYLORIC 300,ZYTEE GEL 10 GM
Patient,,,,,,,,,,,,,,,,,,,,,
,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
SHANKAR SHINDE,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
VISHA KUNAL INGA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
# using the 'apriori algorithm' with min_support=0.01 (1% of 9751)
# It means the item should be present in atleast 97 transaction out of 9751 transactions only when we considered that item in
# frequent itemset
frequent_items = apriori(my_basket_sets, min_support = 0.01,use_colnames = True)
frequent_items

d:\python 37\lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:115: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  DeprecationWarning,

      support                                           itemsets
0    0.077195                                               (10)
1    0.016650                            (2ML SYRINGE          )
2    0.073158                            (5 ML SYRING          )
3    0.014127                            (ACEMIZ MR TAB        )
4    0.010091                            (ALPRAX 0.25          )
..        ...                                                ...
477  0.010091  (INJ FILET 1.GM       , INJ ZYSET            ,...
478  0.011100  (INJ ZYSET            , IV NS 500 ML         ,...
479  0.010091  (IV RL 500            , INJ ZYSET            ,...
480  0.011100  (IV RL 500            , INJ ZYSET            ,...
481  0.010091  (INJ ZYSET            , IV NS 500 ML         ,...

[482 rows x 2 columns]

In [21]:
# now making the rules from frequent itemset generated above

rules = association_rules(frequent_items, metric = "lift", min_threshold = 1)
rules.sort_values('confidence', ascending = False, inplace = True)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
3382,"(CHEST LEEDS , 10, IV NS 100 ...",(INJ ZYSET ),0.010091,0.108981,0.010091,1.000000,9.175926,0.008991,inf
2638,"(INTRACATH NO 22 , INJ ZYSET ,...",(INJ PENTALOC ),0.010595,0.124622,0.010595,1.000000,8.024291,0.009275,inf
2750,"(INJ ZYSET , IV RL 500 ,...",(IV NS 500 ML ),0.012109,0.061049,0.012109,1.000000,16.380165,0.011370,inf
750,"(INJ FILET 1.GM , IV NS 100 )",(INJ PENTALOC ),0.020686,0.124622,0.020686,1.000000,8.024291,0.018108,inf
739,"(INJ FILET 1.GM , INJ ROSINOX 60 )",(INJ PENTALOC ),0.013118,0.124622,0.013118,1.000000,8.024291,0.011483,inf
...,...,...,...,...,...,...,...,...,...
1445,(INJ PENTALOC ),"(10, CHEST LEEDS , IV RL 500 ...",0.124622,0.012614,0.010091,0.080972,6.419433,0.008519,1.074381
3946,(INJ PENTALOC ),"(INJ FILET 1.GM , INJ ZYSET ,...",0.124622,0.010595,0.010091,0.080972,7.642182,0.008770,1.076577
1990,(INJ PENTALOC ),"(5 ML SYRING , IV SET ,...",0.124622,0.012109,0.010091,0.080972,6.686910,0.008582,1.074930
137,(INJ PENTALOC ),(SYRINGE 50ML ),0.124622,0.012109,0.010091,0.080972,6.686910,0.008582,1.074930
885,(INJ PENTALOC ),"(IV NS 500 ML , INJ ROSINOX 60 )",0.124622,0.013118,0.010091,0.080972,6.172532,0.008456,1.073832

In [22]:
# arranging the data from highest to lowest with respect to 'confidence'

rules.sort_values('confidence', ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
3382,"(CHEST LEEDS , 10, IV NS 100 ...",(INJ ZYSET ),0.010091,0.108981,0.010091,1.000000,9.175926,0.008991,inf
991,"(IV RL 500 , INJ ROSINOX 60 )",(IV NS 500 ML ),0.010091,0.061049,0.010091,1.000000,16.380165,0.009475,inf
3018,"(INJ FILET 1.GM , INJ ZYSET ,...",(10),0.012614,0.077195,0.012614,1.000000,12.954248,0.011640,inf
3649,"(INJ ZYSET , IV RL 500 ,...",(IV NS 500 ML ),0.010595,0.061049,0.010595,1.000000,16.380165,0.009949,inf
3439,"(INJ FILET 1.GM , INJ ZYSET ,...",(INJ PENTALOC ),0.011604,0.124622,0.011604,1.000000,8.024291,0.010158,inf
...,...,...,...,...,...,...,...,...,...
4192,(INJ PENTALOC ),"(INJ ZYSET , IV NS 500 ML ,...",0.124622,0.012109,0.010091,0.080972,6.686910,0.008582,1.074930
1685,(INJ PENTALOC ),"(INJ ZYSET , 10, INJ LASIX 40 ...",0.124622,0.013623,0.010091,0.080972,5.943920,0.008393,1.073283
2440,(INJ PENTALOC ),"(IV NS 100 , CHEST LEEDS ,...",0.124622,0.012109,0.010091,0.080972,6.686910,0.008582,1.074930
2621,(INJ PENTALOC ),"(INJ FILET 1.GM , IV SET ,...",0.124622,0.010595,0.010091,0.080972,7.642182,0.008770,1.076577
885,(INJ PENTALOC ),"(IV NS 500 ML , INJ ROSINOX 60 )",0.124622,0.013118,0.010091,0.080972,6.172532,0.008456,1.073832